version: "3.3"
services:
  tomcat:
    image: quitequiet/broadleaf-site-hsqldb-app
    ports:
      - target: 8080
        published: 8080
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
