version: "3.3"
services:
  tomcat:
    image: quitequiet/broadleaf-site-hsqldb-app
    networks:
      - backend
    ports:
      - target: 8080
        published: 8080
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
          
networks:
  backend:
